# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'En_working_plot_setting.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_En_workpoint_setting(object):
    def setupUi(self, En_workpoint_setting):
        En_workpoint_setting.setObjectName("En_workpoint_setting")
        En_workpoint_setting.resize(430, 257)
        self.gridLayout = QtWidgets.QGridLayout(En_workpoint_setting)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(En_workpoint_setting)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(En_workpoint_setting)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(En_workpoint_setting)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(En_workpoint_setting)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(En_workpoint_setting)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(En_workpoint_setting)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 3, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(En_workpoint_setting)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(En_workpoint_setting)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 1, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(En_workpoint_setting)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setSingleStep(10)
        self.horizontalSlider_2.setProperty("value", 50)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setInvertedAppearance(False)
        self.horizontalSlider_2.setInvertedControls(False)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_2.addWidget(self.horizontalSlider_2, 5, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(En_workpoint_setting)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 2, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(En_workpoint_setting)
        self.groupBox.setMinimumSize(QtCore.QSize(80, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setMinimumSize(QtCore.QSize(30, 20))
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setMinimumSize(QtCore.QSize(30, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(En_workpoint_setting)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 1, 1, 1)
        self.horizontalSlider_1 = QtWidgets.QSlider(En_workpoint_setting)
        self.horizontalSlider_1.setMaximum(100)
        self.horizontalSlider_1.setSingleStep(10)
        self.horizontalSlider_1.setProperty("value", 50)
        self.horizontalSlider_1.setTracking(True)
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setInvertedAppearance(False)
        self.horizontalSlider_1.setInvertedControls(False)
        self.horizontalSlider_1.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.gridLayout_2.addWidget(self.horizontalSlider_1, 4, 2, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(En_workpoint_setting)
        QtCore.QMetaObject.connectSlotsByName(En_workpoint_setting)

    def retranslateUi(self, En_workpoint_setting):
        _translate = QtCore.QCoreApplication.translate
        En_workpoint_setting.setWindowTitle(_translate("En_workpoint_setting", "绘图设置"))
        self.label_4.setText(_translate("En_workpoint_setting", "X轴最大范围："))
        self.label_3.setText(_translate("En_workpoint_setting", "绘制BSFC等高线："))
        self.label.setText(_translate("En_workpoint_setting", "X轴分辨率："))
        self.label_2.setText(_translate("En_workpoint_setting", "Y轴分辨率："))
        self.comboBox_2.setItemText(0, _translate("En_workpoint_setting", "10"))
        self.comboBox_2.setItemText(1, _translate("En_workpoint_setting", "20"))
        self.comboBox_2.setItemText(2, _translate("En_workpoint_setting", "50"))
        self.comboBox_2.setItemText(3, _translate("En_workpoint_setting", "100"))
        self.label_5.setText(_translate("En_workpoint_setting", "Y轴最大范围："))
        self.label_7.setText(_translate("En_workpoint_setting", "250"))
        self.comboBox.setItemText(0, _translate("En_workpoint_setting", "10"))
        self.comboBox.setItemText(1, _translate("En_workpoint_setting", "20"))
        self.comboBox.setItemText(2, _translate("En_workpoint_setting", "50"))
        self.comboBox.setItemText(3, _translate("En_workpoint_setting", "100"))
        self.radioButton.setText(_translate("En_workpoint_setting", "Y"))
        self.radioButton_2.setText(_translate("En_workpoint_setting", "N"))
        self.label_6.setText(_translate("En_workpoint_setting", "6000"))

