# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from IconSource import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1259, 914)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Real_Road_FC_tab = QtWidgets.QWidget()
        self.Real_Road_FC_tab.setObjectName("Real_Road_FC_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Real_Road_FC_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.groupBox = QtWidgets.QGroupBox(self.Real_Road_FC_tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_4.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_4.setSizePolicy(sizePolicy)
        self.plainTextEdit_4.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout_3.addWidget(self.plainTextEdit_4, 3, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 0, 1, 1, 1)
        self.open_DRIVER = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_DRIVER.sizePolicy().hasHeightForWidth())
        self.open_DRIVER.setSizePolicy(sizePolicy)
        self.open_DRIVER.setMinimumSize(QtCore.QSize(40, 25))
        self.open_DRIVER.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"")
        self.open_DRIVER.setText("")
        self.open_DRIVER.setObjectName("open_DRIVER")
        self.gridLayout_3.addWidget(self.open_DRIVER, 2, 2, 1, 1)
        self.open_CAR = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_CAR.sizePolicy().hasHeightForWidth())
        self.open_CAR.setSizePolicy(sizePolicy)
        self.open_CAR.setMinimumSize(QtCore.QSize(40, 25))
        self.open_CAR.setMaximumSize(QtCore.QSize(90, 25))
        self.open_CAR.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"\n"
"")
        self.open_CAR.setText("")
        self.open_CAR.setObjectName("open_CAR")
        self.gridLayout_3.addWidget(self.open_CAR, 1, 2, 1, 1)
        self.open_DBC = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_DBC.sizePolicy().hasHeightForWidth())
        self.open_DBC.setSizePolicy(sizePolicy)
        self.open_DBC.setMinimumSize(QtCore.QSize(40, 25))
        self.open_DBC.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"")
        self.open_DBC.setText("")
        self.open_DBC.setObjectName("open_DBC")
        self.gridLayout_3.addWidget(self.open_DBC, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 1, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_3.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_3.setSizePolicy(sizePolicy)
        self.plainTextEdit_3.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_3.addWidget(self.plainTextEdit_3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_3.addWidget(self.plainTextEdit_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton.setStyleSheet("QPushButton{border-image: url(./Image/Set_name.png);}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 3, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pt_traditional = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pt_traditional.setFont(font)
        self.pt_traditional.setChecked(True)
        self.pt_traditional.setObjectName("pt_traditional")
        self.horizontalLayout.addWidget(self.pt_traditional)
        self.pt_hybrid = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pt_hybrid.setFont(font)
        self.pt_hybrid.setObjectName("pt_hybrid")
        self.horizontalLayout.addWidget(self.pt_hybrid)
        self.pt_elec = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pt_elec.setFont(font)
        self.pt_elec.setObjectName("pt_elec")
        self.horizontalLayout.addWidget(self.pt_elec)
        self.gridLayout_3.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.verticalLayout_1.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.verticalLayout_1, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.Real_Road_FC_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(90, 100))
        self.graphicsView.setMaximumSize(QtCore.QSize(100000, 10000))
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.DatatableView = QtWidgets.QTableView(self.Real_Road_FC_tab)
        self.DatatableView.setMaximumSize(QtCore.QSize(2000, 500))
        self.DatatableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.DatatableView.setObjectName("DatatableView")
        self.gridLayout_2.addWidget(self.DatatableView, 1, 0, 1, 2)
        self.tabWidget.addTab(self.Real_Road_FC_tab, "")
        self.Compare_Results_tab = QtWidgets.QWidget()
        self.Compare_Results_tab.setObjectName("Compare_Results_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Compare_Results_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.Compare_Results_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1215, 778))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Compare_Results_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1259, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actiontest2 = QtWidgets.QAction(MainWindow)
        self.actiontest2.setObjectName("actiontest2")
        self.menu_Engine_Working_Dist = QtWidgets.QAction(MainWindow)
        self.menu_Engine_Working_Dist.setObjectName("menu_Engine_Working_Dist")
        self.menu_InputData = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.menu_InputData.setFont(font)
        self.menu_InputData.setObjectName("menu_InputData")
        self.menu_CalData = QtWidgets.QAction(MainWindow)
        self.menu_CalData.setObjectName("menu_CalData")
        self.menu_Exit = QtWidgets.QAction(MainWindow)
        self.menu_Exit.setObjectName("menu_Exit")
        self.menu_Guildlines = QtWidgets.QAction(MainWindow)
        self.menu_Guildlines.setObjectName("menu_Guildlines")
        self.menu_ContactUs = QtWidgets.QAction(MainWindow)
        self.menu_ContactUs.setObjectName("menu_ContactUs")
        self.menu_Shifting_Strategy = QtWidgets.QAction(MainWindow)
        self.menu_Shifting_Strategy.setObjectName("menu_Shifting_Strategy")
        self.menu_Speed_Dist = QtWidgets.QAction(MainWindow)
        self.menu_Speed_Dist.setObjectName("menu_Speed_Dist")
        self.actionSystemGain = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Image/EnergyIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSystemGain.setIcon(icon)
        self.actionSystemGain.setObjectName("actionSystemGain")
        self.actionRide = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/Image/RideIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRide.setIcon(icon1)
        self.actionRide.setObjectName("actionRide")
        self.actiontest_menu = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/Image/Set_name.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontest_menu.setIcon(icon2)
        self.actiontest_menu.setObjectName("actiontest_menu")
        self.menu.addAction(self.menu_InputData)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_Exit)
        self.menu_3.addAction(self.menu_Engine_Working_Dist)
        self.menu_3.addAction(self.menu_Shifting_Strategy)
        self.menu_3.addAction(self.menu_Speed_Dist)
        self.menu_2.addAction(self.menu_CalData)
        self.menu_4.addAction(self.menu_Guildlines)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.menu_ContactUs)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "配置"))
        self.label_3.setText(_translate("MainWindow", "DRIVER 对应表"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "AS24_test_Result"))
        self.label.setText(_translate("MainWindow", "DBC 对应表"))
        self.label_2.setText(_translate("MainWindow", "CAR 对应表"))
        self.label_4.setText(_translate("MainWindow", "存储文件名"))
        self.groupBox_2.setTitle(_translate("MainWindow", "动力总成类型"))
        self.pt_traditional.setText(_translate("MainWindow", "传统"))
        self.pt_hybrid.setText(_translate("MainWindow", "混合动力"))
        self.pt_elec.setText(_translate("MainWindow", "纯电动"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Real_Road_FC_tab), _translate("MainWindow", "Real Road FC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Compare_Results_tab), _translate("MainWindow", "Compare Results"))
        self.menu.setTitle(_translate("MainWindow", "文件 (File)"))
        self.menu_3.setTitle(_translate("MainWindow", "绘图 (Ploting)"))
        self.menu_2.setTitle(_translate("MainWindow", "计算 (Calculation)"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助 (Help)"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actiontest2.setText(_translate("MainWindow", "test2"))
        self.menu_Engine_Working_Dist.setText(_translate("MainWindow", "发动机工况点分布 Engine Work Point Dist."))
        self.menu_InputData.setText(_translate("MainWindow", "导入测试数据 Input Test Data"))
        self.menu_CalData.setText(_translate("MainWindow", "求解 Solution"))
        self.menu_Exit.setText(_translate("MainWindow", "退出"))
        self.menu_Guildlines.setText(_translate("MainWindow", "操作指南 Guildlines"))
        self.menu_ContactUs.setText(_translate("MainWindow", "联系作者 Contact Us!"))
        self.menu_Shifting_Strategy.setText(_translate("MainWindow", "换挡策略分布 Shifting Strategy Dist."))
        self.menu_Speed_Dist.setText(_translate("MainWindow", "速度分布 Speed Dist."))
        self.actionSystemGain.setText(_translate("MainWindow", "SystemGain"))
        self.actionSystemGain.setToolTip(_translate("MainWindow", "SystemGain"))
        self.actionSystemGain.setShortcut(_translate("MainWindow", "F1"))
        self.actionRide.setText(_translate("MainWindow", "Ride"))
        self.actionRide.setToolTip(_translate("MainWindow", "Ride"))
        self.actionRide.setShortcut(_translate("MainWindow", "F2"))
        self.actiontest_menu.setText(_translate("MainWindow", "test_menu"))

